### ISSUE TITLE
Please update so it works with Angular Version 8

### ISSUE THREAD

**Issue by andreElrico** [hivivo/ngx-json-viewer#24]
```
ng update @angular/cli @angular/core
                  Package "@gofynd/angular-json-viewer" has an incompatible peer dependency to "@angular/common" (requires "^4.0.0" (extended), would install "8.0.1").
                  Package "@gofynd/angular-json-viewer" has an incompatible peer dependency to "@angular/core" (requires "^4.0.0" (extended), would install "8.0.1").
                  Package "@gofynd/angular-json-viewer" has an incompatible peer dependency to "@angular/compiler" (requires "^4.0.0" (extended), would install "8.0.1").
                  Package "@gofynd/angular-json-viewer" has an incompatible peer dependency to "@angular/platform-browser" (requires "^4.0.0" (extended), would install "8.0.1").
                  Package "@gofynd/angular-json-viewer" has an incompatible peer dependency to "zone.js" (requires "^0.8.7", would install "0.9.1").
                  Package "@gofynd/angular-json-viewer" has an incompatible peer dependency to "rxjs" (requires "^5.0.0", would install "6.5.2").
```

**Comment by GerkinDev** [comment]
For people needing this, I've openened a PR: https://github.com/hivivo/ngx-json-viewer/pull/27

I've also pushed a build on GitHub for my personnal use, but that you may also use if you want:

```sh
npm install git+https://github.com/GerkinDev/ngx-json-viewer.git#release
```

**Comment by totszwai** [comment]
@GerkinDev I tried to use yours but getting this error...
`Uncaught ReferenceError: global is not defined`

**Comment by totszwai** [comment]
I am using Angular7... and using the original or @GerkinDev's
I am getting the following error:
> Uncaught ReferenceError: global is not defined

Added the following to my polyfills.ts:
`(window as any).global = window;`

But still get the following error:
> Can't bind to 'json' since it isn't a known property of 'ngx-json-viewer'.
